# Generated by Django 5.2.4 on 2025-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_server', models.CharField(max_length=200)),
                ('target_server', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
